### ISSUE TITLE
Student exam does not submit

### ISSUE THREAD

**Issue by egeatay** [shanearcaro/cs490#40]
When an exam is created and a student attempts to take it, the exam page opens and the questions are displayed along with the answer boxes without issues. However, after completing filling the questions with answers, the form fails submit, giving an error message that it failed to submit. There is no row entered in the completedexam table either.

**Comment by egeatay** [comment]
The process does make an entry into StudentExams, which makes the exam listing no longer visible on the students exams page

**Comment by shanearcaro** [comment]
Routing has been fixed and students can now submit exams.

**Comment by egeatay** [comment]
on my end I get the same issue again with the most recent main
